name: 05/28/2016testthegrid
favicon: null
layout_spectrum: 0.650198481278494
typography_spectrum: 0.12302249041385949
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.16380684357136488
  lightness: 0.4037587472703308
  saturation: 0.6135416913311929
  rhythmicContrast: 0.24898942350409925
purpose: []
